
services:
  db:
    image: mysql:8.0.39
    container_name: mysql-aula
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - productsNW
    restart: always
    ports:
      - "3308:3306" # Corrigido para mapear a porta correta do MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products

  api-products:
    build:
      context: ./
    container_name: api-produto
    ports:
      - "8080:8080"
    environment:
      - CORS_ORIGINS=http://localhost:3000,http://localhost
    depends_on:
      - db
    networks:
      - productsNW
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    restart: always

networks:
  productsNW:
    driver: bridge

volumes:
  dbdata:
